repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.0
    hooks:
      - id: ruff
        files: ^(src|test)/
        args: [--fix]
      - id: ruff-format
        files: ^(src|test)/

  - repo: local
    hooks:
      - id: run-unit-tests-with-coverage
        name: Run Unit Tests with Coverage
        entry: ./run_precommit_tests.sh
        language: script
        files: \.py$
        stages: [pre-commit]
        pass_filenames: false
