#!/usr/bin/env python3
"""
Regenerate references/cli-reference.md from live gavel CLI --help output.
Run this script whenever a CLI command is added or changed:

    python scripts/update_cli_reference.py

Writes to: <skill-dir>/references/cli-reference.md
"""
import subprocess
from pathlib import Path

SKILL_DIR = Path(__file__).parent.parent
REFERENCES_DIR = SKILL_DIR / "references"
OUTPUT_FILE = REFERENCES_DIR / "cli-reference.md"

SUBCOMMANDS: list[list[str]] = [
    [],
    ["oneshot"],
    ["oneshot", "create"],
    ["oneshot", "run"],
    ["oneshot", "judge"],
    ["oneshot", "report"],
    ["oneshot", "list"],
    ["oneshot", "milestone"],
    ["conv"],
    ["conv", "create"],
    ["conv", "generate"],
    ["autotune"],
    ["autotune", "create"],
    ["autotune", "run"],
]


def run_help(args: list[str]) -> str:
    result = subprocess.run(
        ["gavel"] + args + ["--help"],
        capture_output=True,
        text=True,
    )
    return result.stdout.strip()


def build_reference() -> str:
    lines: list[str] = [
        "# Gavel CLI Reference",
        "",
        "> Auto-generated by `scripts/update_cli_reference.py`. Do not edit manually.",
        "> Re-run the script after any CLI change.",
        "",
    ]

    for args in SUBCOMMANDS:
        cmd = "gavel " + " ".join(args) if args else "gavel"
        output = run_help(args)
        lines.append(f"## `{cmd}`")
        lines.append("")
        lines.append("```")
        lines.append(output)
        lines.append("```")
        lines.append("")

    return "\n".join(lines)


def main() -> None:
    REFERENCES_DIR.mkdir(parents=True, exist_ok=True)
    content = build_reference()
    OUTPUT_FILE.write_text(content, encoding="utf-8")
    print(f"Written: {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
